language: python

python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

install: 
  - make install
  - pip install coveralls

script: 
  - make test
  - coverage run --source=threadloop setup.py test

after_success:
  - coveralls
